config/routes.rb
Rails.application.routes.draw do
 
 
  resources :carts
  resources :line_items
 root 'catalog#index'
  resources :products
  	root to: 'users#new'

  	get '/profil', to: 'users#edit', as: :profil
  	patch '/profil', to: 'users#update'
  	#session
  	get '/login', to: 'sessions#new', as: :new_session
  	post '/login', to:'sessions#create'
  	delete '/logout', to: 'sessions#destroy', as: :destroy_session

  	resources :passwords, only: [:new, :create, :edit, :update]
	resources :users, only: [:new, :create, :edit]  do 
			member do
				get 'confirm'
			end
		end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Earivo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
   
  </head>

  <body>

    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a href="<%= root_path %>"class="navbar-brand">Earivo</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <%= current_user.username %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Mon profil', profil_path %></li>
                <li><%= link_to 'Se déconnecter', destroy_session_path, data: {method: :delete} %></li>
                
              </ul>
            </li>

          <% else %>

            <li><a href="<%= new_user_path %>">S'inscrire</a></li>
            <li><a href="<%= new_session_path %>">Se connecter</a></li>
          <% end %>

        </ul>
      </div>
    </div>
    <div class="container">
    

      <% if flash[:success] %>
        <div class="alert alert-success">
          <%= flash[:success] %>
        </div>
      <% end %>

      <% if flash[:danger] %>
        <div class="alert alert-danger">
          <%= flash[:danger] %>
        </div>
      <% end %>

      <h1 class="display-1 p-3 bg-secondary text-white rounded">Arts Gasy</h1>
<div class="row">
  <div class="col-3" id="cart">
    <% if @cart && @cart.line_items.any? %>
      <%= render @cart %>
    <% else %>
      <h2>Panier vide</h2>
    <% end %>
  </div>

  <div class="col-9">
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>

    <%= yield %>
  </div>
</div>

   

  </div>

      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>